# Generated by Django 5.2.8 on 2025-11-20 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_services_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaffImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_position', models.CharField(max_length=50)),
                ('staff_pic', models.ImageField(blank=True, null=True, upload_to='uploads/staffImages')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
            options={
                'verbose_name': 'About U',
            },
        ),
    ]
