# Generated by Django 5.2.8 on 2025-11-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addstaffimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='doctors/')),
            ],
        ),
    ]
