# Generated by Django 5.2.8 on 2025-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('', '--Apply for--'), ('Nurse', 'nurse'), ('Others', 'others')], default='--Apply for--', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='uploads/job_applications')),
                ('cover_letter', models.FileField(upload_to='uploads/Cover_letters')),
                ('about_us', models.TextField(max_length=100)),
            ],
        ),
    ]
