# Generated by Django 5.2.8 on 2025-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobapplications'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.CharField(choices=[('Allow', 'Allow'), ('Disable', 'Disable')], max_length=50)),
            ],
            options={
                'verbose_name': 'Allow Job',
            },
        ),
    ]
