# Generated by Django 5.2.8 on 2025-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jobalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(choices=[('Department_team', 'Department_team'), ('Management_Team', 'Management_Team')], default='Choice', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
            ],
        ),
    ]
