# Generated by Django 5.2.8 on 2025-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/')),
                ('Title', models.CharField(max_length=50)),
                ('event_des', models.TextField()),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
