# Generated by Django 5.2.8 on 2025-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('news_date', models.DateTimeField()),
                ('Title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('poster', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
