# Generated by Django 5.2.8 on 2025-11-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
